import json
import os

# Bible books in correct order
books = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1_Samuel",
    "2_Samuel",
    "1_Kings",
    "2_Kings",
    "1_Chronicles",
    "2_Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song_of_Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1_Corinthians",
    "2_Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1_Thessalonians",
    "2_Thessalonians",
    "1_Timothy",
    "2_Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1_Peter",
    "2_Peter",
    "1_John",
    "2_John",
    "3_John",
    "Jude",
    "Revelation"
]

# Mapping book names to book IDs for Sajeevavahini links
book_ids = {
    "Genesis": 1,
    "Exodus": 2,
    "Leviticus": 3,
    "Numbers": 4,
    "Deuteronomy": 5,
    "Joshua": 6,
    "Judges": 7,
    "Ruth": 8,
    "1_Samuel": 9,
    "2_Samuel": 10,
    "1_Kings": 11,
    "2_Kings": 12,
    "1_Chronicles": 13,
    "2_Chronicles": 14,
    "Ezra": 15,
    "Nehemiah": 16,
    "Esther": 17,
    "Job": 18,
    "Psalms": 19,
    "Proverbs": 20,
    "Ecclesiastes": 21,
    "Song_of_Solomon": 22,
    "Isaiah": 23,
    "Jeremiah": 24,
    "Lamentations": 25,
    "Ezekiel": 26,
    "Daniel": 27,
    "Hosea": 28,
    "Joel": 29,
    "Amos": 30,
    "Obadiah": 31,
    "Jonah": 32,
    "Micah": 33,
    "Nahum": 34,
    "Habakkuk": 35,
    "Zephaniah": 36,
    "Haggai": 37,
    "Zechariah": 38,
    "Malachi": 39,
    "Matthew": 40,
    "Mark": 41,
    "Luke": 42,
    "John": 43,
    "Acts": 44,
    "Romans": 45,
    "1_Corinthians": 46,
    "2_Corinthians": 47,
    "Galatians": 48,
    "Ephesians": 49,
    "Philippians": 50,
    "Colossians": 51,
    "1_Thessalonians": 52,
    "2_Thessalonians": 53,
    "1_Timothy": 54,
    "2_Timothy": 55,
    "Titus": 56,
    "Philemon": 57,
    "Hebrews": 58,
    "James": 59,
    "1_Peter": 60,
    "2_Peter": 61,
    "1_John": 62,
    "2_John": 63,
    "3_John": 64,
    "Jude": 65,
    "Revelation": 66
}

# Number of chapters in each book
book_chapters = {
    "Genesis": 50,
    "Exodus": 40,
    "Leviticus": 27,
    "Numbers": 36,
    "Deuteronomy": 34,
    "Joshua": 24,
    "Judges": 21,
    "Ruth": 4,
    "1_Samuel": 31,
    "2_Samuel": 24,
    "1_Kings": 22,
    "2_Kings": 25,
    "1_Chronicles": 29,
    "2_Chronicles": 36,
    "Ezra": 10,
    "Nehemiah": 13,
    "Esther": 10,
    "Job": 42,
    "Psalms": 150,
    "Proverbs": 31,
    "Ecclesiastes": 12,
    "Song_of_Solomon": 8,
    "Isaiah": 66,
    "Jeremiah": 52,
    "Lamentations": 5,
    "Ezekiel": 48,
    "Daniel": 12,
    "Hosea": 14,
    "Joel": 3,
    "Amos": 9,
    "Obadiah": 1,
    "Jonah": 4,
    "Micah": 7,
    "Nahum": 3,
    "Habakkuk": 3,
    "Zephaniah": 3,
    "Haggai": 2,
    "Zechariah": 14,
    "Malachi": 4,
    "Matthew": 28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "1_Corinthians": 16,
    "2_Corinthians": 13,
    "Galatians": 6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "1_Thessalonians": 5,
    "2_Thessalonians": 3,
    "1_Timothy": 6,
    "2_Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "1_Peter": 5,
    "2_Peter": 3,
    "1_John": 5,
    "2_John": 1,
    "3_John": 1,
    "Jude": 1,
    "Revelation": 22
}

# Final JSON structure
all_books_data = {}

# Generate URLs for each book and chapter in Bible order
for book in books:
    book_id = book_ids.get(book)
    chapters_count = book_chapters.get(book, 1)
    
    if book_id is None:
        print(f"⚠️ Book ID not found for {book}")
        continue
    
    chapter_data = {}
    for chapter in range(1, chapters_count + 1):
        url = f'https://hadassahstore.sajeevavahini.com/audiobible/{book_id}/{chapter}.mp3'
        chapter_data[str(chapter)] = url
    
    all_books_data[book] = chapter_data

# Write to a single JSON file
output_dir = 'pleasant_audio_json'
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, 'all_books_ordered.json')

with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(all_books_data, f, indent=4)

print(f'✅ All books JSON generated in Bible order at {output_file}')
